# Generated by Django 3.1.4 on 2022-02-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica_sitios',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
