# Generated by Django 3.1.4 on 2022-02-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_critica_sitios_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica_sitios',
            name='evaluador',
            field=models.CharField(choices=[('Axel E González', 'Axel E González'), ('Bianca E Monrroy', 'Bianca E Monrroy')], default='Bianca E Monrroy', max_length=20),
        ),
    ]
