# Generated by Django 3.1.4 on 2022-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_critica_sitios_evaluador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critica_sitios',
            name='ya_visitado',
        ),
        migrations.AddField(
            model_name='lugares',
            name='ya_visitado',
            field=models.BooleanField(default=False),
        ),
    ]
