# Generated by Django 3.1.4 on 2022-02-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20220223_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares',
            name='ya_visitado',
        ),
        migrations.AddField(
            model_name='critica_sitios',
            name='ya_visitado',
            field=models.BooleanField(default=False),
        ),
    ]
